### ISSUE TITLE
Link to Moondream2 in README is broken

### ISSUE THREAD

**Issue by EvanKrall** [nkasmanoff/pi-card#1]
The markdown for the link is `[Moondream2](moondream.ai)`, and that's being interpreted as a link to `https://github.com/nkasmanoff/pi-card/blob/main/moondream.ai`, which doesn't exist

I'm guessing you meant to link to the domain `moondream.ai`, and throwing `https://` in the front of the domain name would fix it.

**Comment by nkasmanoff** [comment]
Yes thank you! I'll fix that
