### ISSUE TITLE
SD Card size recommendation

### ISSUE THREAD

**Issue by marclundgren** [nkasmanoff/pi-card#10]
I know that ollama models can take up a decent chunk of sd card storage. Do you have a minimum sd card size recommendation for this project? If so, we can add it to the hardware section of README

**Comment by nkasmanoff** [comment]
Hey! Sorry for delayed reply. 

I got a 128GB which came with the kit I got. 

I would say you would be okay with anything over 16GB so long as you don't download and test with too many different Ollama models. I think you'd be in the clear with 32GB, 64GB is more than enough. If I had to recommend it would be 32 or 64 just to be super sure, and I don't think the cost difference is too much for that. Can update the readme later once I have a closer look at the storage profile.
