### ISSUE TITLE
[Question] Would this work on a Raspberry Pi 4B?

### ISSUE THREAD

**Issue by abceleung** [nkasmanoff/pi-card#3]
I have a RPi 4B (4GB) and is wondering if I can use it to build this project. Thanks!

**Comment by nkasmanoff** [comment]
@abceleung I think so! My suggestion would be to pick a different model here (https://github.com/nkasmanoff/pi-card/blob/main/config.py#L16) as this one takes up a lot of RAM, but if you switch to something even smaller, or use a different quantization style which reduces the memory required even more, I think this would work. 

For more models: https://ollama.com/library
